### ISSUE TITLE
Support for OAS 3.1 unevaluatedProperties is missing

### ISSUE THREAD

**Issue by david0** [networknt/openapi-parser#54]
`unevaluatedProperties` was introduced with OpenAPI 3.1. Unfortunately this is not supported by openapi-parser (yet)

**Comment by stevehu** [comment]
@david0 Thanks a lot for pointing it out. We can get the openapi-parse fixed and released in the 2.1.35 release. I also upgraded light-rest-4j to support the OpenAPI 3.1.0 recently.

**Comment by stevehu** [comment]
I have released the 2.1.35-SNAPSHOT version if you want to test it locally. Thanks.

**Comment by david0** [comment]
I tested locally and everything works as expected.

Thank you for all your efforts!
